name: dart

on:
  push:
    paths:
      - 'dart/**'
      - '.github/workflows/dart1.yml'

jobs:
  integration_test:
    runs-on: macos-latest

    steps:

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub upgrade --major-versions
      - run: flutter pub get
      - run: flutter --disable-telemetry

      - run: flutter doctor

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'

  
      - name: Run tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
           api-level: 30
           target: google_apis
           arch: x86_64
           script: ./gradlew connectedCheck

      - run: flutter test --update-goldens integration_test/

      - name: Archive screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: dart/screenshots/
